name:                laughable
version:             0.1.0.0
synopsis:            Clowns to the left of me, jokers to the right
description:         Convert any Traversable into a non-empty variant, a zipper variant, a dissected variant, etc.
homepage:            https://github.com/gelisam/laughable#readme
github:              gelisam/laughable
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Data
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens
  - transformers

library:
  source-dirs:      src
  ghc-options: -W -Wall

tests:
  doctests:
    source-dirs: tests
    main: doctests.hs
    dependencies:
      - doctest
      - doctest-discover
